### ISSUE TITLE
Support for phantom '--web-security' : false

### ISSUE THREAD

**Issue by krunkosaurus** [jdcataldo/grunt-mocha-phantomjs#29]
Can we build in support for disabling security options in phantom within mocha_phantomjs Grunt task options?

**Comment by KrisSiegel** [comment]
Is this meant to still work? This doesn't seem to work as expected with the latest version. I'm getting a `NETWORK_ERR: XMLHttpRequest Exception 101` when attempting to make an AJAX call from tests running with mocha_phantomjs.

**Comment by KrisSiegel** [comment]
Nevermind I figured it out; looks like the syntax is different (that or there is some other way to make the above solution to work and there are two ways to do it).

``` javascript
mocha_phantomjs: {
    options: {
        phantomConfig:{
            "--web-security": false
        }
    },
    files: {
        src: ["test/specRunner.html"]
    }
}
```
