### ISSUE TITLE
Install phantomjs 2.0

### ISSUE THREAD

**Issue by quentindemetz** [jdcataldo/grunt-mocha-phantomjs#33]
How hard is it to implement this?

**Comment by jdcataldo** [comment]
mocha-phantomjs would need to build out the support. You can follow the issue here: https://github.com/metaskills/mocha-phantomjs/issues/175. Once it's supported, I will update the grunt plugin.

**Comment by bithavoc** [comment]
:+1:

**Comment by nathanboktae** [comment]
As discussed in the above issue, the plugins should start to use [mocha-phantomjs-core](https://github.com/nathanboktae/mocha-phantomjs-core), which is ready for consumption now - it supports both phantomjs 1.9.1+ and phantomjs 2.
