### ISSUE TITLE
Reporter output always goes to stdout

### ISSUE THREAD

**Issue by danvk** [jdcataldo/grunt-mocha-phantomjs#34]
I'm using mocha-lcov-reporter and grunt-mocha-phantomjs to generate code coverage data. It works great! But the reported data always gets [dumped to stdout][1], even though I've configured an `output` in my `Gruntfile.js`:

```javascript
mocha_phantomjs: {
  cov: {
    src: ['test/coverage.html'],
    options: {
      reporter: 'node_modules/mocha-lcov-reporter/lib/lcov.js',
      output: 'build/bundled.lcov'
    }
  }
}
```

Is this the desired behavior? Is there any way to force the reporter's output to _just_ go to the file, rather than both to the file and stdout?

[1]: https://travis-ci.org/hammerlab/pileup.js/builds/52165667

**Comment by jdcataldo** [comment]
Would a silent option work for you? Something like:

```javascript
mocha_phantomjs: {
  cov: {
    src: ['test/coverage.html'],
    options: {
      reporter: 'node_modules/mocha-lcov-reporter/lib/lcov.js',
      output: 'build/bundled.lcov',
      silent: true
    }
  }
}
```

**Comment by danvk** [comment]
Absolutely.
