### ISSUE TITLE
Error on new version of mocha-phantom released today

### ISSUE THREAD

**Issue by lmarkus** [jdcataldo/grunt-mocha-phantomjs#36]
```
npm i grunt-mocha-phantomjs
```
As of today, yields:
```
npm ERR! Darwin 14.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "i" "grunt-mocha-phantomjs"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package phantomjs does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer mocha-phantomjs@3.5.4 wants phantomjs@1.9.1 - 1.9.7-15

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lmarkus/dev/scratch/t1/npm-debug.log
```

**Comment by jdcataldo** [comment]
This is an issue with mocha-phantomjs. The phantomjs version is locked down: https://github.com/nathanboktae/mocha-phantomjs/commit/219bc30afa7bb629549fdff89d989e737fa67303. If you have a newer version of phantomjs installed, you will need to downgrade.

**Comment by lmarkus** [comment]
On this particular app, your module is the one that installed phantom, so we don't have control :(
https://github.com/jdcataldo/grunt-mocha-phantomjs/blob/master/package.json#L32

**Comment by jdcataldo** [comment]
Oh right. Thought I removed that.

**Comment by jdcataldo** [comment]
Pushed a new version to match the dependency.

**Comment by lmarkus** [comment]
Sweet thanks!



On Jul 15, 2015, at 6:33 PM, Justin Cataldo <notifications@github.com<mailto:notifications@github.com>> wrote:


Pushed a new version to match the dependency.

-

**Comment by shellscape** [comment]
@jdcataldo please publish 0.6.2, it hasn't hit npm yet

**Comment by jdcataldo** [comment]
Should be published: https://www.npmjs.com/package/grunt-mocha-phantomjs

**Comment by nathanboktae** [comment]
Sorry for doing this in a patch version, my mistake. I've reverted it for `3.5.6`, and restored it in `3.6.0`. @jdcataldo You may need to update your `mocha-phantomjs` dependency to `~3.6.0`
