### ISSUE TITLE
Move to mocha-phantomjs-core

### ISSUE THREAD

**Issue by nathanboktae** [jdcataldo/grunt-mocha-phantomjs#37]
The phantomjs code was separated out from the CLI in `mocha-phantomjs` in preparation for phantomjs2 and to give build plugin authors like you for grunt full control over what version of phantomjs you use, where you get it from, and how you call it. Full discussion is in nathanboktae/mocha-phantomjs#127, and will prevent issues like #36 . 

The main difference is options except reporter and URL are passed as a JSON blob. See [the documentation](https://github.com/nathanboktae/mocha-phantomjs-core), as well as how `gulp-mocha-phantomjs` is [already doing this](https://github.com/mrhooray/gulp-mocha-phantomjs/blob/a0437bba83f6bfb1b6fcb6a0235aa5d087574e9d/index.js#L21-L28)

**Comment by jdcataldo** [comment]
The switch is in the works. Just trying to find the time.

**Comment by nathanboktae** [comment]
Cool, thanks for all the effort :clap:

**Comment by rek** [comment]
Yer much appreciated :clap:

**Comment by jdcataldo** [comment]
Just published a new version using mocha-phantomjs-core. Let me know if you run into any issues.
