### ISSUE TITLE
Latest update broke tests

### ISSUE THREAD

**Issue by bhamodi** [jdcataldo/grunt-mocha-phantomjs#38]
Hey @jdcataldo - the latest update isn't working for me anymore.

I see this in my console when I run my tests now:
```sh
>> Can't open 'node_modules/grunt-mocha-phantomjs/node_modules/mocha-phantomjs/lib/mocha-phantomjs.coffee'
>> Exited with code: 255.
```

**Comment by jdcataldo** [comment]
This is with version 1.0.0? It shouldn't be looking for mocha-phantomjs.coffee.

**Comment by bhamodi** [comment]
Yes this is with v1.0.0, I deleted my `node_modules` directory and did a clean npm install to ensure I got the updated version.

**Comment by bhamodi** [comment]
Actually, hold on, I the issue is from a bad configuration on my end. Let me verify and get back to you.

**Comment by bhamodi** [comment]
Yup, just misconfiguration. Closing this issue.
