### ISSUE TITLE
Get non-zero exit code with output set

### ISSUE THREAD

**Issue by donnielrt** [jdcataldo/grunt-mocha-phantomjs#43]
I see that the task will always complete with a zero code when the [output option is provided](https://github.com/jdcataldo/grunt-mocha-phantomjs#output). Is there a way to coerce a failure, since CircleCI is marking the task as successful?

**Comment by jdcataldo** [comment]
Just published v2.0.0 with a ```failWithOutput``` option. Let me know if you run into any issues.

**Comment by donnielrt** [comment]
Thanks @jdcataldo!
