### ISSUE TITLE
Version of phantom installed

### ISSUE THREAD

**Issue by ekkis** [jdcataldo/grunt-mocha-phantomjs#47]
it seems that this module installs phantomjs.  my question today is: how can I change the version of phantomjs that gets installed?  at present it's 1.9.8 but that version is broken.  see: https://github.com/ariya/phantomjs/issues/12697

so I'd like to downgrade to 1.9.7 but having done:

    # npm uninstall phantomjs
    # npm install phantomjs@1.9.7-15 --save-dev

in my project I still get 1.9.8 to run during tests because the version under grunt-mocha-hpantomjs didn't change.  so how can I change it?

**Comment by jdcataldo** [comment]
Just pushed a new version with a known range of working phantomjs versions. Try grabbing the latest.

**Comment by ekkis** [comment]
that fixed it.  1,000 thanks!
