### ISSUE TITLE
Test coverage with Istanbul?

### ISSUE THREAD

**Issue by franciscop** [jdcataldo/grunt-mocha-phantomjs#63]
Hi, I have been trying to make this work but I haven't been able at all:

``` js
mocha_phantomjs: {
  all: './tests.html',
  options: {
    coverage: {
      reporter: 'istanbul'
    }
  }
}
```

The tests work perfectly, but there's no code coverage at all, which I'd love to have. Do you have any clue how to include it? I'd prefer using Istanbul since I've used it before for pure Node.js testing, but I'm having trouble integrating it with phantomjs. I have tried many different things, but none seem to help me getting closer to make a test coverage:

``` js
mocha_phantomjs: {
  all: './tests.html',
  options: {
    coverage: {
      htmlReport: 'coverage/html'
    }
  }
}
```

**Comment by hcharley** [comment]
I too have had difficulties trying to use this project to get coverage reports. Anyone out there with a secret recipe for this?
